{"name": "test_calc_sum_1[9-9-20]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 18 == 20", "trace": "input1 = 9, input2 = 9, output = 20\n\n    @pytest.mark.parametrize(\"input1, input2, output\",\n                             [\n                                 (3, 5, 8),\n                                 (5, 6, 11),\n                                 (9, 9, 20)\n                             ]\n                             )\n    def test_calc_sum_1(input1, input2, output):\n        result = sum(input1, input2)\n>       assert result == output\nE       assert 18 == 20\n\ntest_parametrization_demo.py:33: AssertionError"}, "parameters": [{"name": "input1", "value": "9"}, {"name": "input2", "value": "9"}, {"name": "output", "value": "20"}], "start": 1574058785954, "stop": 1574058785955, "uuid": "0689cc88-e825-43b3-b216-ed6a4f6f12d4", "historyId": "c54de86583df817e6c313e44aa456fe1", "testCaseId": "ab10348b301c7b2025b2b658292f81da", "fullName": "test_parametrization_demo#test_calc_sum_1", "labels": [{"name": "suite", "value": "test_parametrization_demo"}, {"name": "host", "value": "DESKTOP-EHCDH8A"}, {"name": "thread", "value": "10764-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_parametrization_demo"}]}